version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3
jobs:
  create_infrastructure: 
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-east-1
  
  # Config and Deployment
  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
              fingerprints: f1:9f:0c:e4:ca:47:4b:7a:73:15:d5:18:d0:d2:09:57 
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i inventory.txt main-remote.yml

  smoke_tests:
    docker: 
      - image: python:3.7-alpine3.11
    steps:
      - run: apk add --update curl
      - run:
            name: smoke test
            command:
               URL="https://blog.udacity.com/"
              # Test if website exists
              if curl -s --head ${URL} 
              then
                return 0
              else
                return 1
              fi

workflows:
  myWorkflow:
    jobs:
      - smoke_tests
      