version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3
jobs:
  create_infrastructure: 
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-east-1

  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprint: 74:f1:12:99:e3:96:30:a3:75:0b:ef:cc:8b:44:f2:c4
      - run:
          name: install dependnecies
          command: |
            apl add --update ansible
      - run:
          name: configure server
          command: |
            ansible-playbook -i inventory.txt playbook.yml
workflows:
  myWorkflow:
    jobs:
      - create_infrastructure