version: 2.1

jobs:    
  print-hello:
    # Specifying the executioning env
    docker:
      - image: circleci/node:13.8.0
    # add steps
    steps:
      - run: echo Hello
  print-world:
    # Specifying the executioning env
    docker:
      - image: circleci/node:13.8.0
    # add steps
    steps:
       steps:
      - run: echo World

workflows:
  hello-workflow:
    jobs:
      - print-hello
      - print-world:
          requires:
            - print-hello
