# a job thats uses "command" that prints pipeline to the console
version: 2.1

command:
  print_pipeline_id:
    parameters:
      id:
        type: string
    steps:
     - run: echo ${CIRCLE_WORKFLOW_ID}

jobs:
  mitakeey_job:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id

workflow:
  run_mitakeey_job:
    jobs:
      - mitakeey_job
